name = "test-deploy"
pages_build_output_dir = "./dist"
compatibility_date = "2025-11-20" # Use today's date or later

# Optional: Add account/zone if not using API token
# account_id = "your-account-id"
